# Generated by Django 5.2.6 on 2025-09-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter_finder', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ประเภทสัตว์')),
                ('icon', models.CharField(default='🐾', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PetSitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='แนะนำตัว')),
                ('experience_years', models.PositiveIntegerField(verbose_name='ประสบการณ์ (ปี)')),
                ('location', models.CharField(max_length=100, verbose_name='พื้นที่ให้บริการ')),
                ('hourly_rate_min', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ราคาต่ำสุด/ชม.')),
                ('hourly_rate_max', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ราคาสูงสุด/ชม.')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมรับงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petsitter_finder.user')),
                ('pet_types', models.ManyToManyField(to='petsitter_finder.pettype', verbose_name='ประเภทสัตว์ที่ดูแลได้')),
            ],
        ),
    ]
