# Generated by Django 5.2.6 on 2025-09-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter_finder', '0003_pettype_petsitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='วันเวลาเริ่มต้น')),
                ('end_date', models.DateTimeField(verbose_name='วันเวลาสิ้นสุด')),
                ('pet_name', models.CharField(max_length=50, verbose_name='ชื่อสัตว์เลี้ยง')),
                ('special_instructions', models.TextField(blank=True, verbose_name='คำแนะนำพิเศษ')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคารวม')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('confirmed', 'ยืนยันแล้ว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='petsitter_finder.user')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsitter_finder.pettype')),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='petsitter_finder.petsitter')),
            ],
        ),
    ]
