version: '3.8'

services:
  web:
    image: pckzy/petsitter-finder:latest
    container_name: petsitter_web
    command: gunicorn pettech.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: petsitter_db
    environment:
      POSTGRES_DB: petsitter
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: